[development]
DB_USERNAME="root"
DB_PASSWORD="root"
DB_ENGINE="postgresql+psycopg2"
DB_HOST="localhost"
DB_PORT=5432
DB_NAME="pems_api"
COGNITO_USER_POOL_ID = "ap-south-1_hbbkIzw4t"
ALLOWED_ORIGINS = ["*"]

[testing]
COGNITO_USER_POOL_ID = "ap-south-1_hbbkIzw4t"
ALLOWED_ORIGINS = ["*"]